### ISSUE TITLE
flathub build bots cannot invoke rust-nightly

### ISSUE THREAD

**Issue by muelli** [flathub/flathub#1058]
For some reason, the following manifest works locally but not in the build bots:

https://github.com/flathub/chat.delta.desktop/tree/415512b45fe1224a973a227be658521b9a3deb57

I think it can be boiled down to something like

```
  - name: deltachat-core-rust
    buildsystem: simple
    build-options:
      env:
        CARGO_HOME: /run/build/deltachat-core-rust/cargo
      append-path: /app/lib/sdk/rust-nightly/bin
    build-commands:
      - type -a rustc
      - type -a cargo
      - ls -la /app/lib/sdk/rust-nightly/bin/../lib/libstd-ce15167f7b4c4053.so
      - sha256sum /app/lib/sdk/rust-nightly/bin/../lib/libstd-ce15167f7b4c4053.so
      - ls -la /app/lib/sdk/rust-nightly/bin/../lib/
      - ldd /app/lib/sdk/rust-nightly/bin/../lib/libstd-ce15167f7b4c4053.so
      - ldd /app/lib/sdk/rust-nightly/bin/rustc
      - readelf -Ws  /app/lib/sdk/rust-nightly/bin/../lib/libstd-ce15167f7b4c4053.so
      - objdump -TC  /app/lib/sdk/rust-nightly/bin/../lib/libstd-ce15167f7b4c4053.so
      - rustc --version
      - rustc -vV
      - cargo build -p deltachat_ffi --release
    modules:
      - name: rust-nightly-2019-07-02
        buildsystem: simple
        build-commands:
          - ./install.sh --prefix=/app/lib/sdk/rust-nightly --disable-ldconfig --verbose
        sources:
          - type: archive
            only-arches: ["x86_64"]
            url: https://static.rust-lang.org/dist/2019-07-02/rust-nightly-x86_64-unknown-linux-gnu.tar.xz
            sha256: 6c711fd007acf7d569c01577a757ae73a3812f19b6a004f9ae1fd3e1d1bb0424
    sources:
      - type: archive
        url: https://github.com/deltachat/deltachat-core-rust/archive/1.0.0-alpha.2.tar.gz
        sha256: 7e208b1da7605e73babc2ec0bdc7ea70287bfe224ab87cc621890c433bc604d7
      - generated-sources-rust.json
```

Sorry for not providing a SSCCE, but since I don't know how to build arbitrary manifests in the build bots and I don't want to pollute the namespace of any of the flathub applications I maintain, I cannot easily test whether a minimal manifest builds correctly in the bots.

The build (e.g. <https://flathub.org/builds/#/builders/8/builds/619>) fails when trying to execute (!) rustc:

```
rustc: symbol lookup error: /app/lib/sdk/rust-nightly/bin/../lib/libstd-1d923f2389171316.so: undefined symbol: _ZN58_$LT$std..thread..ThreadId$u20$as$u20$core..fmt..Debug$GT$3fmt17h8873429385a0fe87E
```

The symbol name seems to change between builds. In this particular case, I had the feeling of the symbol being present in the library when reading the objdump -TC output.

There seems to be some difference in how the build sandbox is set up on the build bots to what flatpak-builder does locally.
