### ISSUE TITLE
Provide an extension like org.chromium.Chromium.NativeMessagingHost to org.mozilla.firefox.BaseApp

### ISSUE THREAD

**Issue by proletarius101** [flathub/flathub#2102]
Firefox supports native hosts, too. But it seems neither `org.mozilla.firefox.BaseApp` nor https://searchfox.org/mozilla-central/source/taskcluster/docker/firefox-flatpak provide a Flatpak extension working like `org.chromium.Chromium.NativeMessagingHost`. In fact, I don't even know whether it's as simple as
````

  org.chromium.Chromium.NativeMessagingHost:
    version: '1'
    directory: chromium/native-messaging-hosts
    merge-dirs: native-messaging-hosts
    subdirectories: true
    no-autodownload: true
    autodelete: true
````
because there's no doc about it.

The firefox base app repo's issues section is off, and I don't believe there will be any response if I simply post this on Firefox's Bugzilla without a solution. So I have to post it here.
