### ISSUE TITLE
Generalized black screen in Certain Applications

### ISSUE THREAD

**Issue by hhlp** [flathub/flathub#2751]
System Linux: x64
Dist.: Fedora 35

flatpak version:

``` 
flatpak-selinux-1.12.2-1.fc35.noarch
flatpak-session-helper-1.12.2-1.fc35.x86_64
flatpak-libs-1.12.2-1.fc35.x86_64
flatpak-1.12.2-1.fc35.x86_64
flatpak-builder-1.2.0-1.fc35.x86_64
```

These Applications don't work:

com.axosoft.GitKraken/x86_64/stable
com.bitwarden.desktop/x86_64/stable
com.bluejeans.BlueJeans/x86_64/stable
com.meetfranz.Franz/x86_64/stable
com.skype.Client/x86_64/stable
com.slack.Slack/x86_64/stable
com.spotify.Client/x86_64/stable
im.riot.Riot/x86_64/stable
io.exodus.Exodus/x86_64/stable
io.github.shiftey.Desktop/x86_64/stable
net.cozic.joplin_desktop/x86_64/stable
org.jitsi.jitsi-meet/x86_64/stable
org.signal.Signal/x86_64/stable

Only work with this Parameter Enable:

```
flatpak run --disable-gpu .......
``` 

These Applications work as expected:

com.calibre_ebook.calibre/x86_64/stable althought ebook-viewer doesn't work
com.belmoussaoui.Obfuscate/x86_64/stable
com.discordapp.Discord/x86_64/stable
com.github.robertsanseries.ciano/x86_64/stable
com.gitlab.bitseater.meteo/x86_64/stable
com.jetbrains.DataGrip/x86_64/stable
com.jetbrains.GoLand/x86_64/stable
com.jetbrains.IntelliJ-IDEA-Ultimate/x86_64/stable
com.jetbrains.PhpStorm/x86_64/stable
com.jetbrains.PyCharm-Professional/x86_64/stable
com.jetbrains.WebStorm/x86_64/stable
com.obsproject.Studio/x86_64/stable
de.haeckerfelix.Fragments/x86_64/stable
de.manuel_kehl.go-for-it/x86_64/stable
fr.handbrake.ghb/x86_64/stable
io.brackets.Brackets/x86_64/stable
io.dbeaver.DBeaverCommunity/x86_64/stable
io.github.gitahead.GitAhead/x86_64/stable
io.github.obiwankennedy.HotShots/x86_64/stable
net.ankiweb.Anki/x86_64/stable
net.codeindustry.MasterPDFEditor/x86_64/stable
net.sourceforge.jpdftweak.jPdfTweak/x86_64/stable
org.audacityteam.Audacity/x86_64/stable
org.freeplane.App/x86_64/stable
org.gnome.GTG/x86_64/stable
org.gnome.PasswordSafe/x86_64/stable
org.jdownloader.JDownloader/x86_64/stable
org.ksnip.ksnip/x86_64/stable
org.nmap.Zenmap/x86_64/stable
org.telegram.desktop/x86_64/stable

Regards.,

**Comment by hfiguiere** [comment]
you mention `--disable-gpu` but don't even tell what GPU.

**Comment by hhlp** [comment]
This One

![Captura de pantalla de 2022-01-09 15-46-16](https://user-images.githubusercontent.com/2659606/148746474-9d49bf70-401d-4645-b424-4b5cd1f94322.png)

```
Graphics:  Device-1: NVIDIA GK208B [GeForce GT 730] vendor: Micro-Star MSI driver: nouveau v: kernel
           bus-ID: 2d:00.0 chip-ID: 10de:1287 class-ID: 0300
           Device-2: Logitech HD Webcam C525 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 1-2:3
           chip-ID: 046d:0826 class-ID: 0e02 serial: <filter>
           Display: wayland server: X.Org 1.21.1.4 compositor: gnome-shell driver: loaded: nouveau
           note: n/a (using device driver) - try sudo/root resolution: 1920x1080~75Hz s-dpi: 96
           OpenGL: renderer: NV106 v: 4.3 Mesa 21.3.3 direct render: Yes

```

Regards.,

**Comment by hhlp** [comment]
I've just migrated from 35 to 36 today and did a flatpak update, and this is the progress and still don't work:

com.axosoft.GitKraken/x86_64/stable
com.bluejeans.BlueJeans/x86_64/stable
com.meetfranz.Franz/x86_64/stable
net.cozic.joplin_desktop/x86_64/stable

much better than before.....

Regards.,

**Comment by hhlp** [comment]
This is from fedora 36


![Captura de pantalla de 2022-05-19 10-23-27](https://user-images.githubusercontent.com/2659606/169247930-1c262b88-dbd6-41e0-8cd3-47d0bd061d00.png)


```
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 730] vendor: Micro-Star MSI
    driver: nouveau v: kernel bus-ID: 2d:00.0
  Device-2: Logitech HD Webcam C525 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-2:3
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: gpu: nouveau resolution: 1920x1080~75Hz
  OpenGL: renderer: NV106 v: 4.3 Mesa 22.0.3 direct render: Yes
```
