### ISSUE TITLE
CI: Filter PRs to wiki branches

### ISSUE THREAD

**Issue by tinywrkb** [flathub/flathub#3303]
I have a GitHub workflow pushing commits from a `wiki` branch in the packaging repo to the master branch in the wiki repo.  
This was designed to allow non-collaborator contribution by sending pull requests against a branch in the packaging repo.  
While it works well, flathubbot tries to build the PR, and of course fails, as there's no packaging manifest in the repo.  

Any chance we could have the CI skip PRs to `wiki` branches?

* [Example wiki branch](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/tree/wiki) and [wiki repo](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/wiki)
* [Example pull request](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/pull/42)
* Workflow: `.github/workflows/wiki.yaml`

```yaml
name: Update wiki
on:
  push:
    branches:
      - wiki
  workflow_dispatch: {}
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      EMAIL: github-actions[bot]@users.noreply.github.com
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.repository_owner == 'flathub'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: wiki
          fetch-depth: '0'
      - name: Push to wiki
        run: |
              git remote add wiki_repo https://github-actions[bot]:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git
              git push wiki_repo wiki:master
```
