### ISSUE TITLE
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by LucasXu0** [flathub/flathub#4441]
Hi, there.

I set up the flags to "G_APPLICATION_HANDLES_COMMAND_LINE | G_APPLICATION_HANDLES_OPEN" in my application.cc

```
MyApplication* my_application_new() {
  return MY_APPLICATION(g_object_new(my_application_get_type(),
                                     "application-id", APPLICATION_ID,
                                     "flags", G_APPLICATION_HANDLES_COMMAND_LINE | G_APPLICATION_HANDLES_OPEN,
                                     nullptr));
}
```

It will result in an error when packing with Flatpak Builder.
```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

> Access to the entire bus with --socket=system-bus or --socket=session-bus should be avoided, unless the application is a development tool.

I attempted to include the "--session=session-bus" in the yaml file, and it resolved the issue. However, the documentation suggests that accessing it this way might not be the best solution. Is there any suggestion?

**Comment by JakobDev** [comment]
Did the ID of your Flatpak match the ID of you rApplication?

**Comment by LucasXu0** [comment]
Here's the yml file.

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/flatpak/flatpak-builder/main/data/flatpak-manifest.schema.json

---
app-id: com.example.FlutterApp
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
command: flutter_flatpak_example
separate-locales: false
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --socket=pulseaudio
  - --share=network
  # - --socket=session-bus
modules:
  # FlutterApp
  - name: FlutterApp
    buildsystem: simple
    only-arches:
      - x86_64
    build-commands:
      - "./build-flatpak.sh"
    sources:
      - type: file
        path: ../counter_app/FlutterApp-Linux-Portable.tar.gz
      - type: dir
        path: ../counter_app
      - type: file
        path: build-flatpak.sh
```
