### ISSUE TITLE
Flatpak build failing due to -lstdc++fs

### ISSUE THREAD

**Issue by sebinho** [flathub/flathub#5221]
Hi Guys,

I am quite new to flatpak and I am in the process of making one. I am able to build various sources using `autotools`, `cmake` and also `simple`.
But for a specific source, it systematically fails with the following error message:
```
[ 84%] Linking CXX executable bin/uhdm-dump
[ 84%] Linking CXX executable bin/uhdm-hier
/usr/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lstdc++fs: No such file or directory
collect2: error: ld returned 1 exit status
```
Here is my yaml file.

```
app-id: org.flatpak.test
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
sdk-extensions :
       - org.freedesktop.Sdk.Extension.openjdk
command: /usr/bin/sh
finish-args:
       - --share=network
       - --socket=wayland
       - --socket=fallback-x11
       - --filesystem=home
 
modules:
       # Surelog
       - name: surelog
         buildsystem: simple
         build-commands:
              - PATH=$PATH:/app/jre/bin:/usr/bin make PREFIX=${FLATPAK_DEST} -j16
              - make install PREFIX=${FLATPAK_DEST}
         build-options:
         build-args:
              - --share=network
         sources:
             - type: git
               url: https://github.com/chipsalliance/Surelog.git
               branch: master
```

It requires an extension that can be installed in the command line:
```
flatpak install org.freedesktop.Sdk.Extension.openjdk
```

Could someone help me here? I am not sure what is going wrong.
Thanks for your help
