### ISSUE TITLE
Error on try to compile plib: could not find working GL library

### ISSUE THREAD

**Issue by son-link** [flathub/flathub#622]
Hi. I make a new package, but on try to compile plib with config-opts return this error:
```
checking for glNewList in -lGL... no
checking for glNewList in -lMesaGL... no
configure: error: could not find working GL library
Error: module plib: Child process exited with code 1
```

Those is the lines (get from torcs):

```
- name: plib
    rm-configure: true
    config-opts:
      - CXXFLAGS=-fPIC
      
    sources:
      - type: archive
        url: http://plib.sourceforge.net/dist/plib-1.8.5.tar.gz
        sha1: c2cf7e3e1e58f7b63dae4bb21e4fa82c3e4d4cfc
        
      - type: script
        dest-filename: autogen.sh
        commands: 
          - autoreconf -vfi
```
I compile Glut, GLU and Libxmu before plib
